### ISSUE TITLE
OOS Oneplus 6

### ISSUE THREAD

**Issue by tomimarcincin** [kamikat/OreoTintRemover#1]
Not working on Oneplus 6, module activated but no change.... tint is still here. Can you investigate the problem ?

**Comment by kamikat** [comment]
It's a pity that I don't have any OnePlus device to reproduce the problem. It would be helpful if you can provide the version of your ROM.

**Comment by tomimarcincin** [comment]
Stock OOS 5.1.6 - no errors in Xposed log :/

**Comment by tomimarcincin** [comment]
https://ibb.co/h1ymRo

Tint looks like this.. black wallpaper, black systemUI

**Comment by kamikat** [comment]
According to repositories by @OnePlusOSS, the ROM does not use an extracted color (from wallpaper) for its `ScrimView`. Did you mean to prevent the background from being darkened by removing `ScrimView` completely?

**Comment by tomimarcincin** [comment]
Yes if its possible to do :/ Can you make it ? Or can i make it myself by editing SystemUI ?

**Comment by kamikat** [comment]
I'm afraid I can't. And here's something to try 😄 

- Create plugin hooking `ScrimView` to keep it transparent
- GravityBox or other tweak tools for similar function
