### ISSUE TITLE
Tint appears grey rather than the dark tint from Nougat

### ISSUE THREAD

**Issue by IronPiston** [kamikat/OreoTintRemover#2]
The tint added appears gray rather than the black tint present in Nougat and previous android versions. Is there a way to change the color of the tint?

**Comment by kamikat** [comment]
You can change the color value and compile your own package.

https://github.com/kamikat/OreoTintRemover/blob/6d3c131e3bcf8773f68868c2013454a0e8bf07bf/app/src/main/java/moe/banana/mods/notint/Monkey.java#L27-L31

**Comment by gonzalez950** [comment]
How can I compile my own package?
